# Visit https://github.com/lowlighter/metrics#-documentation for full reference
name: Metrics
on:
  # Schedule updates (every 6 hours)
  schedule: [{cron: "0 */6 * * *"}]
  # Lines below let you run workflow manually and on each commit
  workflow_dispatch:
  push: {branches: ["master", "main"]}
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    concurrency:
      group: metrics-update
      cancel-in-progress: true
    steps:
      - name: Cache dependencies
        uses: actions/cache@v4
        with:
          path: |
            ~/.cache
            ~/.npm
            ~/.local
          key: ${{ runner.os }}-metrics-${{ hashFiles('**/package*.json', '**/*.lock', '**/Gemfile.lock') }}
          restore-keys: |
            ${{ runner.os }}-metrics-
            ${{ runner.os }}-
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}

          # Options
          user: fam007e
          template: classic
          base: header, activity, community, repositories, metadata
          config_timezone: Asia/Dhaka
          plugin_gists: yes
          plugin_habits: yes
          plugin_habits_charts_type: classic
          plugin_habits_days: 14
          plugin_habits_facts: yes
          plugin_habits_from: 200
          plugin_isocalendar: yes
          plugin_isocalendar_duration: full-year
          plugin_lines: yes
          plugin_lines_history_limit: 1
          plugin_lines_repositories_limit: 4
          plugin_lines_sections: base
          plugin_traffic: yes
          plugin_wakatime: yes
          plugin_wakatime_sections: time, projects, projects-graphs, languages, languages-graphs, editors-graphs, os-graphs
          plugin_wakatime_languages_ignored: markdown, plaintext, text, xml, yaml, json
          plugin_wakatime_days: 365
          plugin_wakatime_token: ${{ secrets.WAKATIME_TOKEN }}
